version: '3'
networks:
  app-net:
    driver: bridge
services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - app-net
    volumes:
      - './data:/data/db'
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app-net
    volumes:
      - ./backend/file_store:/file_store
      - ./vars:/vars
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_PORT: ${APP_PORT}
      APP_DSN: ${APP_DSN}
      APP_SERVICE_NAME: ${APP_SERVICE_NAME}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      APP_SALT: ${APP_SALT}
      APP_TOKEN_TTL: ${APP_TOKEN_TTL}
      APP_REFRESH_TOKEN_TTL: ${APP_REFRESH_TOKEN_TTL}
      APP_TOKEN_SECRET: ${APP_TOKEN_SECRET}
      APP_CACHE_DURATION: ${APP_CACHE_DURATION}