version: '3'
networks:
  app-net:
    driver: bridge
services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - app-net
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
  #redis:
  #  container_name: redis
  #  image: redis:4.0-alpine
  #  command:
  #    - 'redis-server'
  #    - '--loglevel ${REDIS_LOGLEVEL:-warning}'
  #    - '--databases 2'
  #    - '--maxmemory ${REDIS_MAXMEM:-50mb}'
  #    - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
  #  networks:
  #    - app-net