// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Analytics analytics
//
// swagger:model Analytics
type Analytics struct {

	// chart info
	ChartInfo []*DayLeadsInfo `json:"chart_info"`

	// month count
	MonthCount float64 `json:"month_count,omitempty"`

	// today count
	TodayCount float64 `json:"today_count,omitempty"`
}

// Validate validates this analytics
func (m *Analytics) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChartInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Analytics) validateChartInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.ChartInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.ChartInfo); i++ {
		if swag.IsZero(m.ChartInfo[i]) { // not required
			continue
		}

		if m.ChartInfo[i] != nil {
			if err := m.ChartInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chart_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chart_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this analytics based on the context it is used
func (m *Analytics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChartInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Analytics) contextValidateChartInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ChartInfo); i++ {

		if m.ChartInfo[i] != nil {
			if err := m.ChartInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chart_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chart_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Analytics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Analytics) UnmarshalBinary(b []byte) error {
	var res Analytics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
