// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreatePosterRequest create poster request
//
// swagger:model CreatePosterRequest
type CreatePosterRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// photo
	Photo string `json:"photo,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this create poster request
func (m *CreatePosterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create poster request based on context it is used
func (m *CreatePosterRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreatePosterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatePosterRequest) UnmarshalBinary(b []byte) error {
	var res CreatePosterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
