// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Editable editable
//
// swagger:model Editable
type Editable struct {

	// height
	Height int64 `json:"height,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// type
	Type int64 `json:"type,omitempty"`

	// value
	Value string `json:"value,omitempty"`

	// width
	Width int64 `json:"width,omitempty"`
}

// Validate validates this editable
func (m *Editable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this editable based on context it is used
func (m *Editable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Editable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Editable) UnmarshalBinary(b []byte) error {
	var res Editable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
