// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetPostersRequest get posters request
//
// swagger:model GetPostersRequest
type GetPostersRequest struct {

	// if active true, returns only active posters, else returns all
	// Example: false
	Active bool `json:"active,omitempty"`

	// title filter
	// Example: Акция
	Name string `json:"name,omitempty"`
}

// Validate validates this get posters request
func (m *GetPostersRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get posters request based on context it is used
func (m *GetPostersRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetPostersRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetPostersRequest) UnmarshalBinary(b []byte) error {
	var res GetPostersRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
