// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HodPhoto hod photo
//
// swagger:model HodPhoto
type HodPhoto struct {

	// id
	ID string `json:"id,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// month id
	MonthID string `json:"month_id,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`
}

// Validate validates this hod photo
func (m *HodPhoto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hod photo based on context it is used
func (m *HodPhoto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HodPhoto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HodPhoto) UnmarshalBinary(b []byte) error {
	var res HodPhoto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
