// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Month month
//
// swagger:model Month
type Month struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// value
	Value int64 `json:"value,omitempty"`

	// year id
	YearID string `json:"year_id,omitempty"`
}

// Validate validates this month
func (m *Month) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this month based on context it is used
func (m *Month) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Month) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Month) UnmarshalBinary(b []byte) error {
	var res Month
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
