// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwapStruct swap struct
//
// swagger:model SwapStruct
type SwapStruct struct {

	// first
	First *SwapItem `json:"first,omitempty"`

	// second
	Second *SwapItem `json:"second,omitempty"`
}

// Validate validates this swap struct
func (m *SwapStruct) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFirst(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecond(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwapStruct) validateFirst(formats strfmt.Registry) error {
	if swag.IsZero(m.First) { // not required
		return nil
	}

	if m.First != nil {
		if err := m.First.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("first")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("first")
			}
			return err
		}
	}

	return nil
}

func (m *SwapStruct) validateSecond(formats strfmt.Registry) error {
	if swag.IsZero(m.Second) { // not required
		return nil
	}

	if m.Second != nil {
		if err := m.Second.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("second")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("second")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this swap struct based on the context it is used
func (m *SwapStruct) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFirst(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSecond(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwapStruct) contextValidateFirst(ctx context.Context, formats strfmt.Registry) error {

	if m.First != nil {
		if err := m.First.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("first")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("first")
			}
			return err
		}
	}

	return nil
}

func (m *SwapStruct) contextValidateSecond(ctx context.Context, formats strfmt.Registry) error {

	if m.Second != nil {
		if err := m.Second.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("second")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("second")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SwapStruct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwapStruct) UnmarshalBinary(b []byte) error {
	var res SwapStruct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
