// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwapItem swap item
//
// swagger:model SwapItem
type SwapItem struct {

	// id
	ID string `json:"id,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`
}

// Validate validates this swap item
func (m *SwapItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this swap item based on context it is used
func (m *SwapItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SwapItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwapItem) UnmarshalBinary(b []byte) error {
	var res SwapItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
