// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Year year
//
// swagger:model Year
type Year struct {

	// id
	ID string `json:"id,omitempty"`

	// value
	Value int64 `json:"value,omitempty"`
}

// Validate validates this year
func (m *Year) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this year based on context it is used
func (m *Year) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Year) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Year) UnmarshalBinary(b []byte) error {
	var res Year
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
