swagger: "2.0"
info:
  version: "1.0.0"
  title: "Landing Backend REST"
host: "localhost:8080"
basePath: /
schemes:
- "http"
securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
paths:
  /login:
    post:
      summary: "authentication path"
      parameters:
        - in: body
          name: params
          schema:
              $ref: '#/definitions/AuthenticateRequest'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: 'регистрация успешна'
          schema:
            $ref: '#/definitions/AuthenticateResponse'
        '403':
          description: 'Authentication Fail'
          schema:
            $ref: '#/definitions/AuthenticateResponse'
        '400':
          description: 'Bad request'
          schema:
            $ref: '#/definitions/AuthenticateResponse'
        '500':
          description: 'Internal Server Error'
  /users:
    put:
      summary: "create user"
      security:
        - Token: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: params
          schema:
            $ref: '#/definitions/UserCreateRequest'
      responses:
        '200':
          description: 'пользователь успешно создан'
          schema:
            $ref: '#/definitions/ResultResponse'
        '400':
          description: 'Bad request'
          schema:
            $ref: '#/definitions/ResultResponse'
        '500':
          description: 'Internal Server Error'
  /ping:
    get:
      summary: "authorization check"
      security:
        - Token: []
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: 'пользователь авторизован'
          schema:
            $ref: '#/definitions/ResultResponse'
        '401':
          description: 'необходимо авторизоваться'
          schema:
            $ref: '#/definitions/ResultResponse'
  #posters
  /posters:
    get:
      summary: "gets filtered posters list"
      tags:
        - posters
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: 'returns filtered posters'
          schema:
            $ref: '#/definitions/GetPostersResponse'
        '400':
          description: 'Bad request'
        '500':
          description: 'Internal Server Error'
    put:
      summary: "create poster"
      security:
        - Token: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      tags:
        - posters
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: The file to upload
        - in: formData
          name: title
          type: string
          required: true
        - in: formData
          name: description
          type: string
          required: true
      responses:
        '200':
          description: 'постер успешно создан'
          schema:
            $ref: '#/definitions/Poster'
        '400':
          description: 'Bad request'
          schema:
            $ref: '#/definitions/ResultResponse'
        '500':
          description: 'Internal Server Error'
    patch:
      summary: "update poster"
      security:
        - Token: []
      tags:
        - posters
      consumes:
         - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: file
          type: file
          required: false
          description: The file to upload
        - in: formData
          name: id
          type: string
          required: true
        - in: formData
          name: title
          type: string
          required: true
        - in: formData
          name: description
          type: string
          required: true
        - in: formData
          name: active
          type: boolean
          required: true
        - in: formData
          name: photo
          type: string
          required: false
        - in: formData
          name: order
          type: integer
          required: true
      responses:
        '200':
          description: 'постер успешно создан'
          schema:
            $ref: '#/definitions/ResultResponse'
        '400':
          description: 'Bad request'
          schema:
            $ref: '#/definitions/ResultResponse'
        '500':
          description: 'Internal Server Error'
  /posters/orders:
    post:
      summary: "updates posters oders"
      security:
        - Token: []
      tags:
        - posters
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: params
          schema:
            $ref: '#/definitions/SwapStruct'
          description: swap item orders
      responses:
        '200':
          description: 'положения успешно обновленны'
          schema:
            $ref: '#/definitions/ResultResponse'
        '400':
          description: 'Bad request'
          schema:
            $ref: '#/definitions/ResultResponse'
        '500':
          description: 'Internal Server Error'
  /posters/{posterID}: 
    get:
      summary: "get poster by id"
      security:
        - Token: []
      tags:
        - posters
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: posterID
          type: string
          required: true
          description: String ID of the poster to get
      responses:
        '200':
          description: 'returns requested poster'
          schema:
            $ref: '#/definitions/Poster'
        '400':
          description: 'Bad request'
        '500':
          description: 'Internal Server Error'
    delete:
      summary: "delete poster by id"
      security:
        - Token: []
      tags:
        - posters
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: posterID
          type: string
          required: true
          description: String ID of the poster to get
      responses:
        '200':
          description: 'returns requested poster'
          schema:
            $ref: '#/definitions/ResultResponse'
        '400':
          description: 'Bad request'
        '500':
          description: 'Internal Server Error'
definitions:
  AuthenticateRequest:
    type: object
    properties:
      login:
        type: string
        example: login
      pass:
        type: string
        example: password
  AuthenticateResponse:
    type: object
    properties:
      token:
        type: string
        example: asdkjkzxcqw1290090
      refresh_token:
        type: string
        example: fewerHHsasqw122231
      error:
        type: string
        example: error
  UserCreateRequest:
    type: object
    properties:
      name:
        type: string
        example: пользователь
      login:
        type: string
        example: login
      pass:
        type: string
        example: password
      role:
        type: string
        example: роль
  ResultResponse:
    type: object
    properties:
      msg:
        type: string
        example: пользователь успешно создан
  GetPostersRequest:
    type: object
    properties:
      active:
        type: boolean
        example: false
        description: if active true, returns only active posters, else returns all
      name:
        type: string
        example: Акция
        description: title filter
  GetPostersResponse:
    type: array
    items:
      $ref: '#/definitions/Poster'
  Poster:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      photo:
        type: string
      active:
        type: boolean
      order:
        type: integer
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      modifiedBy:
        type: string
  SwapStruct:
    type: object
    properties:
      first:
        $ref: '#/definitions/SwapItem'
      second:
        $ref: '#/definitions/SwapItem'
  SwapItem:
    type: object
    properties:
      id:
        type: string
      order:
        type: integer
