// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthenticateRequest authenticate request
//
// swagger:model AuthenticateRequest
type AuthenticateRequest struct {

	// login
	// Example: login
	Login string `json:"login,omitempty"`

	// pass
	// Example: password
	Pass string `json:"pass,omitempty"`
}

// Validate validates this authenticate request
func (m *AuthenticateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this authenticate request based on context it is used
func (m *AuthenticateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthenticateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthenticateRequest) UnmarshalBinary(b []byte) error {
	var res AuthenticateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
